/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Steph_Lab17_Group2_A2;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.Scanner;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

//class AppTest {
//        @Test
//        void testSuccessfulUserLogin() {
//            String username = "user1";
//            String password = "password123";
//            String hashedPassword = Encryption.doMD5Hashing(password);
//
//            assertTrue(App.validateCredentials(username, hashedPassword));
//            assertFalse(App.isAdmin(username, hashedPassword));
//        }
//
//}
