/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Steph_Lab17_Group2_A2;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.Scanner;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class AppTest {
//    @Test
//    void testSuccessfulAdminLogin() {
//        String username = "admin";
//        String password = "admin";
//        String hashedPassword = Encryption.doMD5Hashing(password);
//
//        assertTrue(App.validateCredentials(username, hashedPassword));
//        assertTrue(App.isAdmin(username, hashedPassword));

}
